-- The Spectrum 论坛模块数据库设计
-- 区分 Signal (短情报) 和 Depth (长文章) 两种内容类型

-- 论坛主题表
CREATE TABLE forum_threads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- 作者信息
  author_id UUID REFERENCES profiles(id) NOT NULL,
  is_anonymous BOOLEAN DEFAULT FALSE,
  
  -- 内容类型: signal (短情报) 或 depth (长文章)
  type TEXT NOT NULL CHECK (type IN ('signal', 'depth')),
  
  -- Depth 模式专用分类
  category TEXT CHECK (category IN ('review', 'guide', 'discussion', 'debate', 'question')),
  
  -- 内容字段
  title TEXT, -- Signal 模式可为空
  content_text TEXT NOT NULL, -- 纯文本内容
  content_delta JSONB, -- 富文本 Delta 格式 (Depth 模式)
  summary TEXT, -- AI 生成的摘要
  cover_url TEXT, -- 封面图 (Depth 模式)
  
  -- 关联实体
  linked_entities JSONB DEFAULT '[]', -- [{type: 'event', id: 1}, {type: 'team', id: 2}]
  
  -- AI 生成字段
  ai_tags TEXT[] DEFAULT '{}',
  sentiment_score FLOAT DEFAULT 0.5, -- 0-1, 用于热度算法
  read_time_minutes INT DEFAULT 1, -- AI 预估阅读时长
  embedding VECTOR(1536), -- 向量检索
  
  -- 统计字段
  view_count INT DEFAULT 0,
  like_count INT DEFAULT 0,
  comment_count INT DEFAULT 0,
  share_count INT DEFAULT 0,
  
  -- 来源学院 (用于跨界情报高亮)
  source_college TEXT
);

-- 论坛评论表
CREATE TABLE forum_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  thread_id BIGINT REFERENCES forum_threads(id) ON DELETE CASCADE NOT NULL,
  author_id UUID REFERENCES profiles(id) NOT NULL,
  is_anonymous BOOLEAN DEFAULT FALSE,
  content TEXT NOT NULL,
  parent_id BIGINT REFERENCES forum_comments(id), -- 支持嵌套回复
  like_count INT DEFAULT 0
);

-- 论坛互动表
CREATE TABLE forum_interactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES profiles(id) NOT NULL,
  thread_id BIGINT REFERENCES forum_threads(id) ON DELETE CASCADE,
  comment_id BIGINT REFERENCES forum_comments(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('like', 'bookmark', 'share')),
  UNIQUE(user_id, thread_id, type),
  UNIQUE(user_id, comment_id, type)
);

-- 热门话题表 (AI 聚合相似动态)
CREATE TABLE forum_hot_topics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  title TEXT NOT NULL,
  thread_ids BIGINT[] DEFAULT '{}', -- 聚合的帖子 ID
  heat_score FLOAT DEFAULT 0,
  expires_at TIMESTAMPTZ -- 热门话题过期时间
);

-- 索引
CREATE INDEX idx_forum_threads_type ON forum_threads(type);
CREATE INDEX idx_forum_threads_category ON forum_threads(category);
CREATE INDEX idx_forum_threads_created_at ON forum_threads(created_at DESC);
CREATE INDEX idx_forum_threads_author ON forum_threads(author_id);
CREATE INDEX idx_forum_comments_thread ON forum_comments(thread_id);

-- RLS 策略
ALTER TABLE forum_threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE forum_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE forum_interactions ENABLE ROW LEVEL SECURITY;

-- 所有人可读
CREATE POLICY "Forum threads are viewable by everyone" ON forum_threads
  FOR SELECT USING (true);

CREATE POLICY "Forum comments are viewable by everyone" ON forum_comments
  FOR SELECT USING (true);

-- 登录用户可发帖
CREATE POLICY "Authenticated users can create threads" ON forum_threads
  FOR INSERT WITH CHECK (auth.uid() = author_id);

CREATE POLICY "Authenticated users can create comments" ON forum_comments
  FOR INSERT WITH CHECK (auth.uid() = author_id);

-- 作者可编辑自己的内容
CREATE POLICY "Users can update own threads" ON forum_threads
  FOR UPDATE USING (auth.uid() = author_id);

CREATE POLICY "Users can delete own threads" ON forum_threads
  FOR DELETE USING (auth.uid() = author_id);
