create extension if not exists "uuid-ossp";
create extension if not exists vector;

create table if not exists profiles (
  id uuid references auth.users not null primary key,
  email text not null,
  username text,
  college text,
  major text,
  tags text[] default '{}',
  avatar_url text,
  created_at timestamptz default now()
);

create table if not exists articles (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  author_id uuid references profiles(id),
  title text not null,
  content text,
  summary text,
  poster_url text,
  category text,
  event_time timestamptz,
  location text,
  tags text[],
  college text,
  embedding vector(1536)
);

create index if not exists articles_embedding_idx on articles using hnsw (embedding vector_cosine_ops);

create table if not exists interactions (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id),
  article_id bigint references articles(id),
  type text check (type in ('like', 'bookmark', 'join')),
  created_at timestamptz default now()
);

alter table articles enable row level security;
alter table profiles enable row level security;
alter table interactions enable row level security;

create policy "Public articles are readable" on articles for select using (true);
create policy "Authors manage own articles" on articles for
  insert with check (auth.uid() = author_id),
  update using (auth.uid() = author_id),
  delete using (auth.uid() = author_id);

create policy "Users read self profile" on profiles for select using (auth.uid() = id);
create policy "Users edit self profile" on profiles for
  update using (auth.uid() = id);

create policy "Interactions by owner" on interactions for
  select using (auth.uid() = user_id),
  insert with check (auth.uid() = user_id);
