-- 多成员任务分发及状态确认

create table if not exists team_task_assignees (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  task_id bigint references team_tasks(id) on delete cascade not null,
  member_id uuid references profiles(id) on delete cascade not null,
  assigned_by uuid references profiles(id),
  status text default 'pending' check (status in ('pending', 'in-progress', 'submitted', 'done')),
  unique(task_id, member_id)
);

create index if not exists idx_task_assignees_task on team_task_assignees(task_id);
create index if not exists idx_task_assignees_member on team_task_assignees(member_id);

alter table team_task_assignees enable row level security;

create policy "Team assignees readable" on team_task_assignees
  for select using (
    exists (
      select 1 from team_members tm where tm.team_id = (
        select tt.team_id from team_tasks tt where tt.id = team_task_assignees.task_id
      ) and tm.member_id = auth.uid()
    ) or public.is_team_admin((select team_id from team_tasks where id = team_task_assignees.task_id), auth.uid())
  );

create policy "Admins manage assignees" on team_task_assignees
  for insert with check (
    public.is_team_admin((select team_id from team_tasks where id = team_task_assignees.task_id), auth.uid())
  );

create policy "Admins update assignees" on team_task_assignees
  for update using (
    public.is_team_admin((select team_id from team_tasks where id = team_task_assignees.task_id), auth.uid())
  )
  with check (
    public.is_team_admin((select team_id from team_tasks where id = team_task_assignees.task_id), auth.uid())
  );

create policy "Assignees submit progress" on team_task_assignees
  for update using (auth.uid() = member_id)
  with check (
    auth.uid() = member_id
    and status in ('pending', 'in-progress', 'submitted')
  );
