-- 临时沟通信道：潜在成员 ↔ 队长

create table if not exists public.team_interest_messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  team_id bigint not null references public.teams(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  status text default 'delivered' check (status in ('sending', 'delivered', 'failed')),
  metadata jsonb default '{}'::jsonb
);

create index if not exists idx_team_interest_messages_team_time
  on public.team_interest_messages(team_id, created_at desc);

alter table public.team_interest_messages enable row level security;

-- 任何登录用户都可发起沟通；可选限制：需提前递交 team_applications
create policy "Prospects send interest chat" on public.team_interest_messages
  for insert
  with check (
    auth.uid() = sender_id
    and exists (
      select 1 from public.team_applications ta
      where ta.team_id = team_interest_messages.team_id
        and ta.applicant_id = auth.uid()
    )
  );

-- 允许潜在成员看到自己以及队长的回复
create policy "Prospects read interest chat" on public.team_interest_messages
  for select using (
    sender_id = auth.uid()
    or exists (
      select 1 from public.team_interest_messages tim
      join public.teams t on t.id = tim.team_id
      where tim.id = team_interest_messages.id
        and t.owner_id = auth.uid()
    )
  );

-- 队长可以回复潜在成员
create policy "Owners reply interest chat" on public.team_interest_messages
  for insert
  with check (
    exists (
      select 1 from public.teams t
      where t.id = team_interest_messages.team_id
        and t.owner_id = auth.uid()
    )
  );

-- 队长 & 发送者可查询历史
create policy "Owners read interest chat" on public.team_interest_messages
  for select using (
    sender_id = auth.uid()
    or exists (
      select 1 from public.teams t
      where t.id = team_interest_messages.team_id
        and t.owner_id = auth.uid()
    )
  );

-- 队长可删除不合规消息
create policy "Owners moderate interest chat" on public.team_interest_messages
  for delete using (
    exists (
      select 1 from public.teams t
      where t.id = team_interest_messages.team_id
        and t.owner_id = auth.uid()
    )
  );
