-- 临时私聊/直接消息表
-- 用于发现页面申请者与队长之间的临时沟通

CREATE TABLE IF NOT EXISTS public.direct_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- 发送者和接收者
  sender_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  receiver_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  
  -- 关联的小组（可选，用于申请相关的沟通）
  team_id BIGINT REFERENCES public.teams(id) ON DELETE SET NULL,
  
  -- 消息内容
  content TEXT NOT NULL,
  
  -- 状态
  is_read BOOLEAN DEFAULT FALSE,
  
  -- 确保发送者和接收者不同
  CONSTRAINT different_users CHECK (sender_id != receiver_id)
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_dm_sender ON public.direct_messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_dm_receiver ON public.direct_messages(receiver_id);
CREATE INDEX IF NOT EXISTS idx_dm_team ON public.direct_messages(team_id);
CREATE INDEX IF NOT EXISTS idx_dm_created ON public.direct_messages(created_at DESC);

-- RLS 策略
ALTER TABLE public.direct_messages ENABLE ROW LEVEL SECURITY;

-- 用户可以查看自己发送或接收的消息
CREATE POLICY "Users can view own messages" ON public.direct_messages
  FOR SELECT
  USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

-- 用户可以发送消息
CREATE POLICY "Users can send messages" ON public.direct_messages
  FOR INSERT
  WITH CHECK (auth.uid() = sender_id);

-- 接收者可以标记消息为已读
CREATE POLICY "Receiver can update read status" ON public.direct_messages
  FOR UPDATE
  USING (auth.uid() = receiver_id)
  WITH CHECK (auth.uid() = receiver_id);

-- 创建会话视图（用于获取私聊列表）
CREATE OR REPLACE VIEW public.dm_conversations AS
SELECT DISTINCT ON (conversation_partner)
  CASE 
    WHEN sender_id = auth.uid() THEN receiver_id
    ELSE sender_id
  END AS conversation_partner,
  team_id,
  content AS last_message,
  created_at AS last_message_at,
  CASE 
    WHEN receiver_id = auth.uid() AND NOT is_read THEN TRUE
    ELSE FALSE
  END AS has_unread
FROM public.direct_messages
WHERE sender_id = auth.uid() OR receiver_id = auth.uid()
ORDER BY conversation_partner, created_at DESC;
