-- 扩展 articles 表，支持 AI 评分
alter table if exists public.articles
  add column if not exists ai_score numeric default 0;

update public.articles set ai_score = coalesce(ai_score, 0);

alter table if exists public.interactions
  add constraint interactions_unique unique (user_id, article_id, type);

-- 推荐函数：根据用户标签与 AI 评分排序
create or replace function public.recommend_articles(user_id uuid, limit_count int default 4)
returns setof public.articles
language plpgsql
stable
security definer
set search_path = public as $$
declare
  v_tags text[] := '{}';
begin
  select coalesce(tags, '{}') into v_tags
  from public.profiles
  where id = user_id;

  return query
  select *
  from public.articles
  order by
    case when array_length(v_tags, 1) is not null and tags && v_tags then 1 else 0 end desc,
    coalesce(ai_score, 0) desc,
    created_at desc
  limit greatest(1, coalesce(limit_count, 4));
end;
$$;

grant execute on function public.recommend_articles(uuid, int) to anon, authenticated;

-- 组队协作：teams & team_members
create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  owner_id uuid references public.profiles(id) not null,
  name text not null,
  description text,
  type text not null check (type in (
    'project','competition','research','study','meal','sports','carpool','gaming'
  )),
  college text,
  tags text[] default '{}',
  required_skills text[] default '{}',
  current_members int default 1,
  max_members int not null default 5 check (max_members > 0),
  status text not null default 'recruiting' check (status in ('recruiting','full','completed')),
  deadline date,
  is_vibe boolean default false
);

create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  team_id bigint references public.teams(id) on delete cascade not null,
  member_id uuid references public.profiles(id) on delete cascade not null,
  role text,
  skills text[] default '{}',
  status text not null default 'approved' check (status in ('applied','approved','rejected')),
  is_owner boolean default false,
  joined_at timestamptz default now(),
  unique(team_id, member_id)
);

create index if not exists idx_teams_type on public.teams(type);
create index if not exists idx_teams_college on public.teams(college);
create index if not exists idx_team_members_team on public.team_members(team_id);

-- 更新时间触发器
create or replace function public.set_current_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_teams_set_updated
  before update on public.teams
  for each row execute function public.set_current_timestamp();

-- 自动把创建者加入成员表
create or replace function public.add_team_owner_member()
returns trigger
language plpgsql
as $$
begin
  insert into public.team_members(team_id, member_id, role, status, is_owner)
  values (new.id, new.owner_id, '发起人', 'approved', true)
  on conflict (team_id, member_id) do nothing;
  return new;
end;
$$;

create trigger trg_add_owner_member
  after insert on public.teams
  for each row execute function public.add_team_owner_member();

-- 自动刷新团队人数与状态
create or replace function public.refresh_team_member_count()
returns trigger
language plpgsql
as $$
declare
  v_team_id bigint;
  v_member_count int;
begin
  v_team_id := coalesce(new.team_id, old.team_id);
  select count(*) into v_member_count
  from public.team_members
  where team_id = v_team_id and status = 'approved';

  update public.teams
  set current_members = v_member_count,
      status = case
        when status = 'completed' then status
        when v_member_count >= max_members then 'full'
        else 'recruiting'
      end,
      updated_at = now()
  where id = v_team_id;

  return null;
end;
$$;

create trigger trg_team_members_refresh
  after insert or delete or update on public.team_members
  for each row execute function public.refresh_team_member_count();

-- RLS 设置
alter table public.teams enable row level security;
alter table public.team_members enable row level security;

drop policy if exists "Teams readable by everyone" on public.teams;
create policy "Teams readable by everyone" on public.teams
  for select using (true);

drop policy if exists "Owners manage own teams" on public.teams;
create policy "Owners manage own teams" on public.teams
  for update using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id);

drop policy if exists "Owners create teams" on public.teams;
create policy "Owners create teams" on public.teams
  for insert with check (auth.uid() = owner_id);

drop policy if exists "Owners delete teams" on public.teams;
create policy "Owners delete teams" on public.teams
  for delete using (auth.uid() = owner_id);

drop policy if exists "Team members visible" on public.team_members;
create policy "Team members visible" on public.team_members
  for select using (true);

drop policy if exists "Users join team" on public.team_members;
create policy "Users join team" on public.team_members
  for insert with check (auth.uid() = member_id);

drop policy if exists "Members manage own membership" on public.team_members;
create policy "Members manage own membership" on public.team_members
  for delete using (
    auth.uid() = member_id
    or auth.uid() = (select owner_id from public.teams where id = team_id)
  );

drop policy if exists "Owners approve members" on public.team_members;
create policy "Owners approve members" on public.team_members
  for update using (auth.uid() = (select owner_id from public.teams where id = team_id))
  with check (auth.uid() = (select owner_id from public.teams where id = team_id));

-- Forum 补充策略
drop policy if exists "Forum interactions readable" on public.forum_interactions;
create policy "Forum interactions readable" on public.forum_interactions
  for select using (auth.uid() = user_id);

drop policy if exists "Forum interactions insert" on public.forum_interactions;
create policy "Forum interactions insert" on public.forum_interactions
  for insert with check (auth.uid() = user_id);

drop policy if exists "Forum interactions delete" on public.forum_interactions;
create policy "Forum interactions delete" on public.forum_interactions
  for delete using (auth.uid() = user_id);

drop policy if exists "Forum comments update own" on public.forum_comments;
create policy "Forum comments update own" on public.forum_comments
  for update using (auth.uid() = author_id);

drop policy if exists "Forum comments delete own" on public.forum_comments;
create policy "Forum comments delete own" on public.forum_comments
  for delete using (auth.uid() = author_id);

alter table public.forum_hot_topics enable row level security;
drop policy if exists "Hot topics readable" on public.forum_hot_topics;
create policy "Hot topics readable" on public.forum_hot_topics
  for select using (true);
