-- 协作空间模块：申请 / 聊天 / 任务 / 文件

create table if not exists team_applications (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  team_id bigint references teams(id) on delete cascade not null,
  applicant_id uuid references profiles(id) on delete cascade not null,
  message text,
  status text default 'pending' check (status in ('pending', 'approved', 'rejected')),
  mode text default 'focus' check (mode in ('focus', 'vibe')),
  extra jsonb default '{}'::jsonb
);

create index if not exists idx_team_applications_team on team_applications(team_id);
create index if not exists idx_team_applications_applicant on team_applications(applicant_id);

create table if not exists team_chat_messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  team_id bigint references teams(id) on delete cascade not null,
  sender_id uuid references profiles(id) on delete cascade not null,
  content text not null,
  attachments jsonb default '[]'::jsonb,
  status text default 'delivered' check (status in ('sending', 'delivered', 'failed'))
);

create index if not exists idx_team_chat_messages_team_time on team_chat_messages(team_id, created_at desc);

create table if not exists team_tasks (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  team_id bigint references teams(id) on delete cascade not null,
  title text not null,
  status text default 'todo' check (status in ('todo', 'in-progress', 'done')),
  assignee_id uuid references profiles(id),
  due_date date,
  order_index int default 0,
  created_by uuid references profiles(id)
);

create index if not exists idx_team_tasks_team on team_tasks(team_id);

create table if not exists team_files (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  team_id bigint references teams(id) on delete cascade not null,
  uploader_id uuid references profiles(id) on delete cascade not null,
  file_name text not null,
  file_url text not null,
  file_size bigint,
  mime_type text,
  meta jsonb default '{}'::jsonb
);

create index if not exists idx_team_files_team on team_files(team_id);

alter table team_applications enable row level security;
alter table team_chat_messages enable row level security;
alter table team_tasks enable row level security;
alter table team_files enable row level security;

create policy "Team members can view applications" on team_applications
  for select using (
    exists (
      select 1 from team_members tm
      where tm.team_id = team_applications.team_id and tm.member_id = auth.uid()
    ) or exists (
      select 1 from teams t where t.id = team_applications.team_id and t.owner_id = auth.uid()
    ) or auth.uid() = applicant_id
  );

create policy "Applicants insert applications" on team_applications
  for insert with check (auth.uid() = applicant_id);

create policy "Owners update applications" on team_applications
  for update using (
    exists (
      select 1 from teams t where t.id = team_applications.team_id and t.owner_id = auth.uid()
    )
  );

create policy "Team members read chat" on team_chat_messages
  for select using (
    exists (
      select 1 from team_members tm where tm.team_id = team_chat_messages.team_id and tm.member_id = auth.uid()
    ) or exists (select 1 from teams t where t.id = team_chat_messages.team_id and t.owner_id = auth.uid())
  );

create policy "Team members send chat" on team_chat_messages
  for insert with check (
    exists (
      select 1 from team_members tm where tm.team_id = team_chat_messages.team_id and tm.member_id = auth.uid()
    ) or exists (select 1 from teams t where t.id = team_chat_messages.team_id and t.owner_id = auth.uid())
  );

create policy "Team members view tasks" on team_tasks
  for select using (
    exists (
      select 1 from team_members tm where tm.team_id = team_tasks.team_id and tm.member_id = auth.uid()
    ) or exists (select 1 from teams t where t.id = team_tasks.team_id and t.owner_id = auth.uid())
  );

create policy "Team members manage tasks" on team_tasks
  for insert with check (
    exists (
      select 1 from team_members tm where tm.team_id = team_tasks.team_id and tm.member_id = auth.uid()
    ) or exists (select 1 from teams t where t.id = team_tasks.team_id and t.owner_id = auth.uid())
  );

create policy "Team members update tasks" on team_tasks
  for update using (
    exists (
      select 1 from team_members tm where tm.team_id = team_tasks.team_id and tm.member_id = auth.uid()
    ) or exists (select 1 from teams t where t.id = team_tasks.team_id and t.owner_id = auth.uid())
  );

create policy "Team members view files" on team_files
  for select using (
    exists (
      select 1 from team_members tm where tm.team_id = team_files.team_id and tm.member_id = auth.uid()
    ) or exists (select 1 from teams t where t.id = team_files.team_id and t.owner_id = auth.uid())
  );

create policy "Team members upload files" on team_files
  for insert with check (
    exists (
      select 1 from team_members tm where tm.team_id = team_files.team_id and tm.member_id = auth.uid()
    ) or exists (select 1 from teams t where t.id = team_files.team_id and t.owner_id = auth.uid())
  );
